### ISSUE TITLE
关于您Blog中的VNCTF2021 whitegive

### ISSUE THREAD

**Issue by FantasqueX** [TearsJin/TearsJin.github.io#1]
在使用下式计算p时，第二步推导中$(k_1p+1)^e$为什么指数e没有了呢？

({k_1p+1 \over e})^e  = hint + k_2n \Rightarrow (k_1p+1) = e^e(hint + k_2n) \\ \Rightarrow (k_1-e^ek_2q)p = e^e \cdot hint - 1

我看您blog中没有留下邮箱就只能发issue了，还望您指导

**Comment by TearsJin** [comment]
啊... 这里应该是我写错了
是这样的, 利用二项式定理展开(kp+1)^e
(kp)^e+ a1 * (kp)^(e-1) + a2 * (kp)^(e-2)+...+a1* kp + 1
除了最后一项, 其他项都是p的倍数, 那么整个展开式就可以看成Kp+1了

**Comment by FantasqueX** [comment]
> 啊... 这里应该是我写错了
> 是这样的, 利用二项式定理展开(kp+1)^e
> (kp)^e+ a1 * (kp)^(e-1) + a2 * (kp)^(e-2)+...+a1* kp + 1
> 除了最后一项, 其他项都是p的倍数, 那么整个展开式就可以看成Kp+1了

懂了，谢谢您
